### ISSUE TITLE
Feature: User can search character

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/guess-that-rick#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can search for characters.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can type character into input to receive results

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-10 at 4 01 36 PM](https://user-images.githubusercontent.com/85080021/141212883-94dcf1f1-b9f5-45aa-b461-1021dba08f8d.png)

![Screen Shot 2021-11-10 at 4 01 59 PM](https://user-images.githubusercontent.com/85080021/141212892-9f12f1db-c70b-4d1a-b0bb-3d2236fa52ca.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML Dashboard
- [x] Add event listener to dashboard
- [x] Create Search character view in HTML
- [x] Add data.js file with data model
- [x] Switch view to character search upon clicking search characters
- [x] Update views in data.js
- [x] Create form for user search input and collect data in object
- [x] Create dummy entry for search results
- [x] Send network request to Api
- [x] Create DOM tree for rendered search results
- [x] Switch view to search results upon clicking submit
- [x] Update view to results view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
