### ISSUE TITLE
Feature: User can view game characters

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/guess-that-rick#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details about the characters in the game they played.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

At the end of each game, Users will have an option to view characters and will be able to see details about each of those characters.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-16 at 10 15 12 AM](https://user-images.githubusercontent.com/85080021/142042375-418cd6e9-1675-48f0-b866-8d0ec33c542d.png)

![Screen Shot 2021-11-16 at 10 15 24 AM](https://user-images.githubusercontent.com/85080021/142042393-1478a703-c062-460d-a195-6359fba89552.png)

![Screen Shot 2021-11-16 at 10 15 31 AM](https://user-images.githubusercontent.com/85080021/142042434-af4ea5f4-66a7-451a-bfa7-6867907d9749.png)

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add button on modal to 'View Characters'
- [x] Add event listener to button
- [x] Add new view in HTML with data view 'character-list'
- [x] Update view in local storage when clicked
- [x] Create dummy character details card
- [x] Keep track of each character that is shown throughout the quiz
- [x] Create Dom tree with data received from each character shown in quiz and append it to the view list upon clicking 'View Characters'
- [x] Create modal with character details to show upon clicking a character
- [x] Add button to close modal to allow user to click on different characters.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
