### ISSUE TITLE
Feature: User can add character to favorites

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/guess-that-rick#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to save characters from the quiz to be viewed on another page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user sees the list of characters they were quizzed on, they may choose to save that characters information.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-17 at 3 10 04 PM](https://user-images.githubusercontent.com/85080021/142297200-38fb73e9-c356-44a6-91a6-f1989eb50461.png)

![Screen Shot 2021-11-17 at 3 10 15 PM](https://user-images.githubusercontent.com/85080021/142297211-576d1496-842e-491e-9cb0-cdb7ad885bc6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add 'save to favorites' button when the card modal for character info appears
- [x] Add event listener to button
- [x] Create new property on data model that saves favorites
- [x] If clicked, store that character in data model
- [x] Remove event listener on button
- [x] Change text content to say 'saved'
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
