### ISSUE TITLE
Feature: User can view favorites

### ISSUE THREAD

**Issue by addy-abid** [AddyAbid/guess-that-rick#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view list of saved characters
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users may click the 'My Characters' tab and be directed to a page that shows all of the characters they saved
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-11-17 at 5 02 45 PM](https://user-images.githubusercontent.com/85080021/142332225-0cc8541b-cb0b-4476-8eb5-52958d0c8d2e.png)

![Screen Shot 2021-11-17 at 5 03 03 PM](https://user-images.githubusercontent.com/85080021/142332238-b0d66cb9-f337-4764-a9ae-d6420169ad68.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Update view when user clicks 'My Characters' tab
- [x] render Dom tree with characters saved in data model
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
